### ISSUE TITLE
Issues building the project?

### ISSUE THREAD

**Issue by jrkuhn** [mainigautam/instagram_backup_manager#12]
I do not see a 'build' script within the /server/package.json, and have been unsuccessful in finding a node command to do so.
Could you tell me how you are able to recompile and rebuild the project.

I'd like to extend the client/component/Messages2.json to include more information from messages, however I am not able to see my changes without rebuilding the static routes in the /server.

Thanks, any insight would be appreciated, your project is just what I was looking for.
-Justin

**Comment by mainigautam** [comment]
Hi , Thank you for reaching out
To rebuild the project you need to use the client folder and use "npm run build" command to get a "/build" directory which then needs to be replaced with the already existing folder in /server/routes/ named the same (build). 

To see the changes without rebuilding the Frontend again you can add proxy in package.json file of client folder (refer [https://create-react-app.dev/docs/proxying-api-requests-in-development/](here) ) as http://localhost:8081/ and utilize the  react's hot reload with any loss of original application code. as sole purpose of client directory is provide code for development.

Other than that , I'll love to hear what information you need from the messages and I myself will add them. 
for any further problem you can reach me via telegram https://t.me/mainigautam
