### ISSUE TITLE
Instagram Backup Manager not rendering stories, reels and profile pictures.

### ISSUE THREAD

**Issue by nairadithya** [mainigautam/instagram_backup_manager#14]
Hi, the tool works great for messages but I can't view my stories and reels. It's all empty placeholders. 

![Screenshot_20230109_215528](https://user-images.githubusercontent.com/98505663/211357446-02c667e0-9975-425c-b6c2-9b6b954ef6bb.png)

**Comment by mainigautam** [comment]
Ok , I'll Look into this . It'd be great if you can provide screenshot of folder structure or the Picture from Console from Browser
and what date is the backup taken on?

**Comment by mainigautam** [comment]
> Hi, the tool works great for messages but I can't view my stories and reels. It's all empty placeholders.
> 
> ![Screenshot_20230109_215528](https://user-images.githubusercontent.com/98505663/211357446-02c667e0-9975-425c-b6c2-9b6b954ef6bb.png)

Well I Tried With a Backup of mine From 31/Dec/2022 and Works fine , Lemme Know if it's more recent than that

**Comment by nairadithya** [comment]
> > Hi, the tool works great for messages but I can't view my stories and reels. It's all empty placeholders.
> > ![Screenshot_20230109_215528](https://user-images.githubusercontent.com/98505663/211357446-02c667e0-9975-425c-b6c2-9b6b954ef6bb.png)
> 
> Well I Tried With a Backup of mine From 31/Dec/2022 and Works fine , Lemme Know if it's more recent than that

Yes it's a few days newer.

**Comment by nairadithya** [comment]
> Ok , I'll Look into this . It'd be great if you can provide screenshot of folder structure or the Picture from Console from Browser and what date is the backup taken on?

I received the backup on 9th January, 2023.

![Screenshot_20230113_022606](https://user-images.githubusercontent.com/98505663/212179464-8cfdb97b-e55f-41f8-bae2-9298fd45ede1.png)

I hope this is what you were asking for.

**Comment by mainigautam** [comment]
> > Ok , I'll Look into this . It'd be great if you can provide screenshot of folder structure or the Picture from Console from Browser and what date is the backup taken on?
> 
> I received the backup on 9th January, 2023.
> 
> ![Screenshot_20230113_022606](https://user-images.githubusercontent.com/98505663/212179464-8cfdb97b-e55f-41f8-bae2-9298fd45ede1.png)
> 
> I hope this is what you were asking for.

Yes , That's Exactly what I need , I'll fix and update the issue . You can visit repo in 2-3 days again

**Comment by mainigautam** [comment]
@AdithyaNair1234 I have tried backups from Multiple Users downloaded today only , Including business accounts too . I'll Suggest you to download Your Data Again and try , because Everything is working as expected in tests and for other users . If still you face any issues you can open a new issue or contact me on Telegram as @mainigautam for now I am Closing this issue
