### ISSUE TITLE
Error running the app

### ISSUE THREAD

**Issue by daniel-alomar** [mainigautam/instagram_backup_manager#2]
After run 'npm start' it doesn't start and I get an error:

"no s'ha trobat l'ordre" means command not found

(~/Desktop/IG/igbm)─(7 files, 40Kb)─> npm start

> igbm@1.0.0 start /home/daniel/Desktop/IG/igbm
> concurrently - kill-others "npm run server" "npm run client"

sh: concurrently - kill-others: no s'ha trobat l'ordre
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! igbm@1.0.0 start: `concurrently - kill-others "npm run server" "npm run client"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the igbm@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2020-10-07T19_34_49_169Z-debug.log

[2020-10-07T19_34_49_169Z-debug.log](https://github.com/mainigautam/instagram_backup_manager/files/5343416/2020-10-07T19_34_49_169Z-debug.log)

Log attached

**Comment by mainigautam** [comment]
This Error Is Because of dependencies are not installed correctly
