### ISSUE TITLE
friends images can be grabbed if the links are still vailed.

### ISSUE THREAD

**Issue by minanagehsalalma** [mainigautam/instagram_backup_manager#4]
this an html file generated from the zip file using a tool a friend provided a year ago and it shows the images with no problem.... ( note the file is generated  a long time ago)
![image](https://user-images.githubusercontent.com/20546638/100024431-6df2e280-2def-11eb-8a87-222a83757ace.png)

"it dosen't provide the likes, comments and the pictures sent by your friends and i cannot do anything about the stuff instagram itself dosen't provide"

why are you saying this ? 

while the same image in your tool 
![image](https://user-images.githubusercontent.com/20546638/100024592-c88c3e80-2def-11eb-85db-0925f3f135b0.png)

edit : tested the tool again and it shows image not available looks like it used to download the images from the links first but the links have Expiration date i think.

**Comment by mainigautam** [comment]
Actually Brother , The media links are the links of Cached Media and not proper media links and when you access them without auth. token i.e your id and password or an signed Instagram's Official API you don't get access to the media files that are not yours . whereas the one that are yours are already downloaded . 

Comments and likes both the json files are there in backup but only "time" and "text" parameters are given by which they cannot be processed unless or until a "post" key or other parameters are given . 

and instagram backup zips are offline not online or something you need to login for .
For Instance take my example where i had permanently deleted my instagram account but had backup file so i can access it for those who already have their account running backup makes no sense so keeping all that in mind the app is designed however i am constantly working to improve this so maybe in further versions more of data can be processed but i can assure you it's more than 65% already

and the image is just to show that a media is supposed to be here but it is not it's static html and css not dynamic media request or links 

Hope This Clears the doubts and Keep giving feedback it helps a lot !

Thank You

**Comment by minanagehsalalma** [comment]
> it's static html and css not dynamic media request or links

so why don't you get it to request them in the generating process 

> signed Instagram's Official API

does it have to be from the account or ? 

@mainigautam  take a look on the tool
[instabook_full.zip](https://github.com/mainigautam/instagram_backup_manager/files/5591137/instabook_full.zip)

in case of the account not deleted yet .. grabbing the images from the DMs using an api or whatever would be useful.

**Comment by mainigautam** [comment]
> so why don't you get it to request them in the generating process

Because It will need login to accounts. I will implement it for once and give a test . if it's safe and works!

> does it have to be from the account or ?

for private pics , from the account and for open ones a API Signed Token from my end.

> in case of the account not deleted yet .. grabbing the images from the DMs using an api or whatever would be useful.

Will Try Implemenation for once

and ya send me a link to the software i'd be better ,as i can't risk when person i am talking to loves Pen-Testing 😆 
P.S: no offence Please

**Comment by minanagehsalalma** [comment]
> Because It will need login to accounts

@mainigautam  no it doesn't try it yourself ... grab a link of an image sent by a friend and try to open it after signing out and you will see that it opens just normal.

it doesn't require an api from the account or anything. 

>i am talking to loves Pen-Testing 😆

lol dude it's not even mine ( the tool) ... it's similar to your tool but grabs the images of friends dms too... test it even on a dummy account or a vm ... you can grab its code using a debugger i think.

>P.S: no offence Please

lol no worries.

**Comment by mainigautam** [comment]
> @mainigautam no it doesn't try it yourself ... grab a link of an image sent by a friend and try to open it after signing out and you will see that it opens just normal.

Yes , You are right but , servers work on cache based data so it will expire anyhow after sometime . but from this i'll add the feature so that one's who have the image time left can see it 👍 

> lol dude it's not even mine ( the tool) ... it's similar to your tool but grabs the images of friends dms too... test it even on a dummy account or a vm ... you can grab its code using a debugger i think.

Just Kidding Man I Already tested it 😄 

P.S : btw. Is it fine overall? means should i continue ?

**Comment by minanagehsalalma** [comment]
> so it will expire anyhow after sometime . but from this i'll add the feature so that one's who have the image time left can see it

even if it expires after 24 hour of the backup it would still be useful as you can generate file after the backup and save it for later.

> Just Kidding Man I Already tested it 😄

lol

> P.S : btw. Is it fine overall? means should i continue ?

yeah great work mate keep it up.

**Comment by mainigautam** [comment]
@minanagehsalalma Update ! Now Supports Media from Friends too

**Comment by minanagehsalalma** [comment]
@mainigautam tested it .. works but can make the images bigger or even open them in a new tab ... they are more like thumbnails .

**Comment by mainigautam** [comment]
> @mainigautam tested it .. works but can make the images bigger or even open them in a new tab ... they are more like thumbnails .

ok , stay tuned for next 2-3 commits . You can press the star or watch button on the repo . I'll add it
