### ISSUE TITLE
Could not proxy request /upload

### ISSUE THREAD

**Issue by Zezo47** [mainigautam/instagram_backup_manager#5]
Ive no idea of coding etc. i just wanted to read my Instagram backups in a simple way. 
I followed every step and managed to get to the point where i can upload my .zip file. 
First when i tried to upload it said "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:9000/.
[2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED )".
After googling a bit i found out to change the local host from 9000 to 3000 in the package.json (idk if this was right).
Now it uploads but at some point (mostly 32%) it stops and the cmd says "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:3000/.
[2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET)."

Maybe im just dumb but i really want to see my Instagram Backup file and sorry if bothering with "noob" questions^^

**Comment by mainigautam** [comment]
> Ive no idea of coding etc. i just wanted to read my Instagram backups in a simple way.
> I followed every step and managed to get to the point where i can upload my .zip file.
> First when i tried to upload it said "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:9000/.
> [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED )".
> After googling a bit i found out to change the local host from 9000 to 3000 in the package.json (idk if this was right).
> Now it uploads but at some point (mostly 32%) it stops and the cmd says "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:3000/.
> [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET)."
> 
> Maybe im just dumb but i really want to see my Instagram Backup file and sorry if bothering with "noob" questions^^

It is totally no problem asking questions , but would be great if you attach a screenshot or a log file of the error you are having ,

one more thing whether you zipped the files manually or you are giving zip downloaded from Instagram itself to the upload page 

and no worries asking questions , you can spam the issues section the thing is you must be able to use it.

**Comment by Zezo47** [comment]
> > Ive no idea of coding etc. i just wanted to read my Instagram backups in a simple way.
> > I followed every step and managed to get to the point where i can upload my .zip file.
> > First when i tried to upload it said "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:9000/.
> > [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED )".
> > After googling a bit i found out to change the local host from 9000 to 3000 in the package.json (idk if this was right).
> > Now it uploads but at some point (mostly 32%) it stops and the cmd says "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:3000/.
> > [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET)."
> > Maybe im just dumb but i really want to see my Instagram Backup file and sorry if bothering with "noob" questions^^
> 
> It is totally no problem asking questions , but would be great if you attach a screenshot or a log file of the error you are having ,
> 
> one more thing whether you zipped the files manually or you are giving zip downloaded from Instagram itself to the upload page
> 
> and no worries asking questions , you can spam the issues section the thing is you must be able to use it.

Hi,

thank you. When i upload my downloaded unedited zip file the cmd says the error in the screenshot.
![error](https://user-images.githubusercontent.com/77328666/104344197-22120f00-54fd-11eb-99eb-d104d4c3a753.png)

**Comment by Zezo47** [comment]
> > Ive no idea of coding etc. i just wanted to read my Instagram backups in a simple way.
> > I followed every step and managed to get to the point where i can upload my .zip file.
> > First when i tried to upload it said "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:9000/.
> > [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED )".
> > After googling a bit i found out to change the local host from 9000 to 3000 in the package.json (idk if this was right).
> > Now it uploads but at some point (mostly 32%) it stops and the cmd says "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:3000/.
> > [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET)."
> > Maybe im just dumb but i really want to see my Instagram Backup file and sorry if bothering with "noob" questions^^
> 
> It is totally no problem asking questions , but would be great if you attach a screenshot or a log file of the error you are having ,
> 
> one more thing whether you zipped the files manually or you are giving zip downloaded from Instagram itself to the upload page
> 
> and no worries asking questions , you can spam the issues section the thing is you must be able to use it.

Thank you!
I get this error when i try to upload the unedited zip file.
![error](https://user-images.githubusercontent.com/77328666/104344378-5dacd900-54fd-11eb-989e-ba0142104012.png)

**Comment by mainigautam** [comment]
> > > Ive no idea of coding etc. i just wanted to read my Instagram backups in a simple way.
> > > I followed every step and managed to get to the point where i can upload my .zip file.
> > > First when i tried to upload it said "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:9000/.
> > > [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED )".
> > > After googling a bit i found out to change the local host from 9000 to 3000 in the package.json (idk if this was right).
> > > Now it uploads but at some point (mostly 32%) it stops and the cmd says "Proxy error: Could not proxy request /upload from localhost:3000 to http://localhost:3000/.
> > > [2] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET)."
> > > Maybe im just dumb but i really want to see my Instagram Backup file and sorry if bothering with "noob" questions^^
> > 
> > 
> > It is totally no problem asking questions , but would be great if you attach a screenshot or a log file of the error you are having ,
> > one more thing whether you zipped the files manually or you are giving zip downloaded from Instagram itself to the upload page
> > and no worries asking questions , you can spam the issues section the thing is you must be able to use it.
> 
> Thank you!
> I get this error when i try to upload the unedited zip file.
> ![error](https://user-images.githubusercontent.com/77328666/104344378-5dacd900-54fd-11eb-989e-ba0142104012.png)

To Help you i'll need either the whole text from your console window or the debug file from here 

![image](https://user-images.githubusercontent.com/28294883/104349951-9f537900-5529-11eb-816e-28b7007b7e44.png)
