### ISSUE TITLE
[Fixed-27012021][CONFIRMED] Direct message parse error for backups taken in 2021

### ISSUE THREAD

**Issue by Deleora** [mainigautam/instagram_backup_manager#6]
When I click on the Direct button the server tries to parse the messages JSon file but after some time I get the following error:

```
[1] SyntaxError: Unexpected end of JSON input
[1]     at JSON.parse (<anonymous>)
[1]     at C:\Users\Labtop\Documents\GitHub\instagram_backup_manager\server\api\routes\messages.js:12:23
[1]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

What is causing this issue? Any help is appreciated.

**Comment by mainigautam** [comment]
> When I click on the Direct button the server tries to parse the messages JSon file but after some time I get the following error:
> 
> ```
> [1] SyntaxError: Unexpected end of JSON input
> [1]     at JSON.parse (<anonymous>)
> [1]     at C:\Users\Labtop\Documents\GitHub\instagram_backup_manager\server\api\routes\messages.js:12:23
> [1]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
> ```
> 
> What is causing this issue? Any help is appreciated.

Please Make sure your messages.json file is not edited in someway , and are you able to read some messages or not at all? and please provide a little brief error log , so i can check in depth , 

Take the backup once again In case to make sure there is no error in it

**Comment by Deleora** [comment]
> Please Make sure your messages.json file is not edited in someway , 

I've not edited any part of the backup and the backup was download today morning itself.
**Edit**: The 'Profile' and 'Stories' tab seems to be working fine.


> and are you able to read some messages or not at all? 

I'm not seeing anything on the browser tab. However, the `cmd` that runs in the background (when `run.bat` is clicked) loads my messages from the `JSON` and displays it until I get the error I shared above. And probably because of this I only see a Instagram logo on my browser tab and nothing else.


> and please provide a little brief error log , so i can check in depth ,

How can I proved the log you need? I shared the error which I got on my `cmd` terminal.


> Take the backup once again In case to make sure there is no error in it

Ok I'll try this too.

Cheers

**Comment by mainigautam** [comment]
> > Please Make sure your messages.json file is not edited in someway ,
> 
> I've not edited any part of the backup and the backup was download today morning itself.
> **Edit**: The 'Profile' and 'Stories' tab seems to be working fine.
> 
> > and are you able to read some messages or not at all?
> 
> I'm not seeing anything on the browser tab. However, the `cmd` that runs in the background (when `run.bat` is clicked) loads my messages from the `JSON` and displays it until I get the error I shared above. And probably because of this I only see a Instagram logo on my browser tab and nothing else.
> 
> > and please provide a little brief error log , so i can check in depth ,
> 
> How can I proved the log you need? I shared the error which I got on my `cmd` terminal.
> 
> > Take the backup once again In case to make sure there is no error in it
> 
> Ok I'll try this too.
> 
> Cheers

I'll Check it Once Again with the latest backup of my account, there may be possibility of  Instagram making changes to backup itself.  and do revert back if anything works on your end ,

**Comment by mainigautam** [comment]
@Deleora  I have looked into issue and it turns out to be true that Backups Dated in 2021 are not working for now , 
Instagram has adapted new backup format , so i'l try to add it to IGBM ASAP

I will try fix this asap and fix the issue , Stay Tuned will update here

**Comment by mainigautam** [comment]
@Deleora  Updated it now you can use it , Still any issue? Feel Free to Open One Again . 

Hope You Like it This Time 😊
