### ISSUE TITLE
DM threads with specific type of folder name are not parsed

### ISSUE THREAD

**Issue by Deleora** [mainigautam/instagram_backup_manager#7]
Hi,

So I downloaded my data and when I was trying to access a specific person's DM I realized it wasn't being parsed by your tool. I tried to find out the reason for that and I found something though I'm not sure if it's the actual reason for such behavior.

Look here 👇🏻
![image](https://user-images.githubusercontent.com/60055475/106706818-405bbe00-6616-11eb-909f-e0f9a539a201.png)
This is the one which is not shown in your tool. I think because it does not have any `username` part in it's folder name like this one 👇🏻 for example
![image](https://user-images.githubusercontent.com/60055475/106707010-86188680-6616-11eb-90d1-e74dab6f4b7c.png)

Please share your thoughts on this and also how I can view such chats from your tool.
PS: I've not edited a single thing in the backup. Everything is as it was downloaded. Also, this is the only folder with such naming.

Thanks a loads!

**Comment by mainigautam** [comment]
I'll Have a look and Try to Help ASAP ,

**Comment by mainigautam** [comment]
![image](https://user-images.githubusercontent.com/28294883/106750734-39e93880-664e-11eb-9c2a-65b9269bde6e.png)

I tried Reproducing the folder name but seems that it is working , 

You Can Reopen Issue If Problem still persists

**Comment by Deleora** [comment]
> ![image](https://user-images.githubusercontent.com/28294883/106750734-39e93880-664e-11eb-9c2a-65b9269bde6e.png)
> 
> I tried Reproducing the folder name but seems that it is working ,
> 
> You Can Reopen Issue If Problem still persists

Yeah I checked again, it's working. Maybe I missed it the last time. Sorry for the trouble 😥
And Thanks for letting me know.!!
