### ISSUE TITLE
Module not found: Can't resolve './Reels'

### ISSUE THREAD

**Issue by Deleora** [mainigautam/instagram_backup_manager#8]
Hi,

I cloned your repo and ran the `setup.bat` file, everything was fine. But, when I ran `run.bat` after a while I get the **Module not found: Can't resolve './Reels'** error

I've attached 2 screenshots, one of PowerShell and other of browser tab which is opened automatically.
PowerShell
![image](https://user-images.githubusercontent.com/60055475/106722581-262cda80-662c-11eb-970b-d3e12b2f9029.png)

Browser (http://localhost:3000/)
![image](https://user-images.githubusercontent.com/60055475/106723060-b9661000-662c-11eb-833d-12d1d07b5d97.png)

PS: This repo used to work around 10 days ago, I think the error is because of some changes that were committed to the repo later on.

Please share your thoughts on this.
Thanks!

**Comment by mainigautam** [comment]
My Bad ! 
Forgot to Push , Thanks For Pointing Out and Using IGBM

**Comment by Deleora** [comment]
No worries. So can I use it now?
